# Generated by Django 4.2.1 on 2025-10-27 20:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ('-fecha_ingreso', 'nombre')},
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(default='Sin marca', max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_ingreso',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
