# Generated by Django 5.2.6 on 2025-10-29 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_seed_productos_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='ciudad_envio',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='compra',
            name='correo_contacto',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='compra',
            name='direccion_envio',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='compra',
            name='nombre_completo',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='compra',
            name='notas_extra',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='compra',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
