# Generated by Django 5.2.6 on 2025-10-30 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_compra_ciudad_envio_compra_correo_contacto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostulacionVendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('tienda', models.CharField(blank=True, max_length=120)),
                ('instagram', models.CharField(blank=True, max_length=180)),
                ('mensaje', models.TextField(blank=True)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='nuevo', max_length=20)),
            ],
            options={
                'ordering': ('-fecha_envio',),
            },
        ),
    ]
