# Generated by Django 5.2.6 on 2025-10-30 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_postulacionvendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacionvendedor',
            name='notas',
            field=models.TextField(blank=True, help_text='Notas internas del equipo'),
        ),
    ]
