# Generated by Codex assistant
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_postulacionvendedor_notas'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fecha_suscripcion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-fecha_suscripcion',),
            },
        ),
    ]
