# Generated by Django 5.2.6 on 2025-11-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_newslettersubscriber_segmento_ruta_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilcliente',
            name='foto',
            field=models.ImageField(blank=True, help_text='Fotografía de perfil usada en el área de cliente.', null=True, upload_to='perfiles/'),
        ),
    ]
