# Generated by Django 5.2.6 on 2025-11-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_perfilcliente_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='estado_entrega',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('enviado', 'Enviado'), ('entregado', 'Entregado')], default='pendiente', help_text='Estado actual del despacho del pedido.', max_length=20),
        ),
    ]
